import { Entity, Column, PrimaryColumn, BeforeInsert, BaseEntity } from 'typeorm'
import { v4 as uuidv4 } from 'uuid'

// each entity is more or less a table in the database
// BaseEntity is a class which has a bunch of methods like User.create()
// optional users is the name of the table
@Entity('users')
export class User extends BaseEntity {
  // a random string generated by the system
  @PrimaryColumn('uuid') id: string

  @Column('varchar', { length: 255 })
  email: string

  @Column('text') password: string

  // BeforeInsert will run and do anything right before it is inserted into database
  @BeforeInsert()
  addId() {
    this.id = uuidv4()
  }
}
